baseURL = "https://lightbi-beta-demo.netlify.app/"
languageCode = "en"
title = "Palabra"
theme = "lightbi-hugo"
summaryLength  = "30"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
ignoreLogs = ['warning-goldmark-raw-html']


[Params]
selfHosted = true
mainSections = ["posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
hideAuthor = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
gcse = false
Lastmod = false
rss = false 
pagination = "10"
description="Your can add your website description here."
lunrSearch = true
previewCardImagePlacement = "bottom"
hidePostImage = false
tagSubtitle = "Here, you’ll discover the latest notes that explore new insights, and unique perspectives on the world."
homepageLayout = "profile"
profileShortbio = "Helping organizations bridge programming, data analysis, and documentation—turning complexity into clear, effective solutions that connect teams and customers."
profilePhoto = "img/profile/home-profile-pic.jpg"

[pagination]
pagerSize = 9



[Params.Author]
  name = "Craig Frayne"
  website = "https://www.binovarghese.com/"
  authorInfo = "Give everything for your dreams."
  authorPostImage = "/img/author-post-img.jpg"
  #youtube = "user/username" # or channel/channelname
  #linkedin = "username"
  github = "craigmateo"
  #codepen = "cfrayne"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "/posts/"
    weight = 3

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5


